#!/usr/bin/with-contenv sh

INSTALL_JAVA8=${INSTALL_JAVA8:-false}
INSTALL_JAVA16=${INSTALL_JAVA16:-true}

echo '
-------------------------------------
Installing Java runtime
-------------------------------------'

if [ "$INSTALL_JAVA8" = true ] && [ ! -d "/usr/lib/jvm/java-1.8-openjdk" ]; then
  echo '
Installing Java 8...
-------------------------------------'
  apk add --no-cache openjdk8-jre
fi

if [ -d "/usr/lib/jvm/java-1.8-openjdk" ]; then
  echo '
-------------------------------------
Java 8 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA16" = true ] && [ ! -d "/usr/lib/jvm/java-16-openjdk" ]; then
  echo '
Installing Java 16...
-------------------------------------'
  apk add --no-cache openjdk16-jre-headless
fi

if [ -d "/usr/lib/jvm/java-16-openjdk" ]; then
  echo '
-------------------------------------
Java 16 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA8" = false ] && [ "$INSTALL_JAVA16" = false ]; then
  echo 'Both environment variables INSTALL_JAVA8 and INSTALL_JAVA16 have been set to false! Skipping Java runtime install...
-------------------------------------'
fi
