#!/usr/bin/with-contenv sh

INSTALL_JAVA11=${INSTALL_JAVA11:-false}
INSTALL_JAVA16=${INSTALL_JAVA16:-true}

echo '
-------------------------------------
Installing Java runtime
-------------------------------------'

if [ "$INSTALL_JAVA11" = true ] && [ ! -d "/usr/lib/jvm/java-11-openjdk" ]; then
  echo '
Installing Java 11...
-------------------------------------'
  apk add --no-cache openjdk11-jre-headless
fi

if [ -d "/usr/lib/jvm/java-11-openjdk" ]; then
  echo '
-------------------------------------
Java 11 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA16" = true ] && [ ! -d "/usr/lib/jvm/java-16-openjdk" ]; then
  echo '
Installing Java 16...
-------------------------------------'
  apk add --no-cache openjdk16-jre-headless
fi

if [ -d "/usr/lib/jvm/java-16-openjdk" ]; then
  echo '
-------------------------------------
Java 16 has been installed...
-------------------------------------'
fi

if [ "$INSTALL_JAVA11" = false ] && [ "$INSTALL_JAVA16" = false ]; then
  echo 'Both environment variables INSTALL_JAVA11 and INSTALL_JAVA16 have been set to false! Skipping Java runtime install...
-------------------------------------'
fi
